### ISSUE TITLE
Enable plugin automatically?

### ISSUE THREAD

**Issue by Blaisorblade** [ThoughtWorksInc/sbt-api-mappings#1]
Would you make the plugin auto-enabled?

[From](http://www.scala-sbt.org/0.13/docs/Plugins.html), it looks like adding:
```
override def trigger = allRequirements
```
would be enough for that.

**Comment by Atry** [comment]
What makes you thought it should be auto-enabled or not?

**Comment by Atry** [comment]
What makes you thought it should be auto-enabled or not?

**Comment by Atry** [comment]
What makes you thought it should be auto-enabled or not?

**Comment by Blaisorblade** [comment]
I see no use case for adding this plugin to your project and then not enabling it, as in many other plugins, which are then automatically enabled. To disable it, you can disable the `addSbtPlugins`.

Now, in multi-project builds, you can enable the plugin only in some subprojects. Still, what's the use case?

By contrast, https://github.com/sbt/sbt-git contains additional plugins that are not autoenabled — but that's because they're extra and bundled together.

**Comment by Blaisorblade** [comment]
Thanks!

**Comment by Atry** [comment]
Thank you!
