### ISSUE TITLE
handle linking to Javadoc for Java standard library

### ISSUE THREAD

**Issue by SethTisue** [ThoughtWorksInc/sbt-api-mappings#6]
would be cool. as per e.g. http://stackoverflow.com/questions/16934488/how-to-link-classes-from-jdk-into-scaladoc-generated-doc

**Comment by Atry** [comment]
I thought it's a bug in Scaladoc tools per se:
https://github.com/scala/bug/issues/9842

It affects not only JavaDoc URLs but also Scaladoc 2.12 URLs

**Comment by ashawley** [comment]
Yes, links created by Scaladoc need to be fixed.  When the scheme for links is fixed, it will match the JDK link scheme.  That is a good thing.  However, this is a feature request to support Java standard library linking in sbt's `apiMappings`, not a bug report.

**Comment by Atry** [comment]
Sure, the api-mapping for JDK should be added

**Comment by Atry** [comment]
Done.

See
https://github.com/ThoughtWorksInc/sbt-api-mappings/blob/HEAD/src/main/scala/com/thoughtworks/sbtApiMappings/BootstrapApiMappings.scala
